spring.application.name=sharded-ledger
spring.flyway.enabled=false

logging.pattern.level=%5p [%X{shard:-no-shard}]

app.datasource.shard0.url=jdbc:postgresql://localhost:5432/ledger
app.datasource.shard0.username=user
app.datasource.shard0.password=password

app.datasource.shard1.url=jdbc:postgresql://localhost:5433/ledger
app.datasource.shard1.username=user
app.datasource.shard1.password=password

app.datasource.shard2.url=jdbc:postgresql://localhost:5434/ledger
app.datasource.shard2.username=user
app.datasource.shard2.password=password
